language: generic
sudo: required
services:
  - docker

before_install:
  - docker image build -t HiepCongChua/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true HiepCongChua/docker-react npm run test
