language: generic
sudo: required
services:
  - docker

before_install:
  - docker image build -t hieple/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true hieple/docker-react npm run test
deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-1"
  app: "docker"
  env: "Docker-env-1"
  bucket_name: "elasticbeanstalk-ap-southeast-1-191868485217"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY
